### ISSUE TITLE
Will be nice to have sort option

### ISSUE THREAD

**Issue by TSEVER** [tr1ckyf0x-studio/wakeonlan-ios#50]
Hi it is an amazing app in a small size thanks. It might be very nice to have an option to sort the devices. Every new device comes to top and no way to move.

**Comment by tr1ckyf0x** [comment]
@TSEVER Thank you for the issue. The bugfix #46, required to be merged prior to implementing reordering, will be merged soon, and then we will be able to implement sorting. I expect sorting to be implemented in the next release.

**Comment by tr1ckyf0x** [comment]
Implemented. #69

**Comment by tr1ckyf0x** [comment]
Will be published in next release
